version: '3'
services:
  netdisco-db:
    image: netdisco-db:latest
    build:
      context: .
      dockerfile: netdisco-db/Dockerfile
    volumes:
      - "./netdisco/data:/var/lib/postgresql/data"
  netdisco-base:
    image: netdisco-base:latest
    build:
      context: .
      dockerfile: netdisco-base/Dockerfile
  netdisco-backend:
    image: netdisco-backend:latest
    build:
      context: .
      dockerfile: netdisco-backend/Dockerfile
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - netdisco-db:db
