version: '3'
services:
  netdisco-db:
    image: netdisco-db:latest
    build:
      context: netdisco-db
    volumes:
      - "./netdisco/pgdata:/var/lib/postgresql/data"
  netdisco-base:
    image: netdisco-base:latest
    build:
      context: netdisco-base
  netdisco-backend:
    image: netdisco-backend:latest
    build:
      context: netdisco-backend
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - netdisco-db:db
