version: '3'
#volumes:
#  config-volume:
#    - type: bind
#      source: "./netdisco/config"
#      target: "/home/netdisco/environments"
services:
  postgres:
    image: docker.io/postgres:9.6.6-alpine
    environment:
      - POSTGRES_USER=netdisco
      - POSTGRES_PASSWORD=netdisco
    volumes:
      - "./netdisco/data:/var/lib/postgresql/data"
  netdisco-base:
    image: netdisco-base:latest
    build:
      context: .
      dockerfile: Dockerfile-netdisco-base
  netdisco-web:
    image: netdisco-web:latest
    build:
      context: .
      dockerfile: Dockerfile-netdisco-web
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    environment:
      - NETDISCO_ADMIN_USER=admin
      - NETDISCO_ADMIN_PASS=admin
    depends_on:
      - netdisco-base
    links:
      - postgres:db
    ports:
      - "5000:5000"
  netdisco-backend:
    image: netdisco-backend:latest
    build:
      context: .
      dockerfile: Dockerfile-netdisco-backend
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - postgres:db
