version: '3'
services:
  postgres:
    image: docker.io/postgres:9.6.6-alpine
    environment:
      - POSTGRES_USER=netdisco
      - POSTGRES_PASSWORD=netdisco
    volumes:
      - "./netdisco/data:/var/lib/postgresql/data"
  netdisco-base:
    image: netdisco-base:latest
    build:
      context: .
      dockerfile: netdisco-base/Dockerfile
  netdisco-backend:
    image: netdisco-backend:latest
    build:
      context: .
      dockerfile: netdiso-backend/Dockerfile
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - postgres:db
