version: '2.3'
services:
  netdisco-postgresql:
    image: netdisco:latest-postgresql
    build:
      context: netdisco-postgresql
    volumes:
      - "./netdisco/pgdata:/var/lib/postgresql/data"
#  netdisco-base:
#    image: netdisco:latest-base
#    build:
#      context: netdisco-base
  netdisco-backend:
    image: netdisco:latest-backend
    build:
      context: netdisco-backend
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    environment:
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql
  netdisco-web:
    image: netdisco:latest-web
    build:
      context: netdisco-web
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    environment:
      NETDISCO_DB_HOST: netdisco-postgresql
    ports:
      - "5000:5000"
    depends_on:
      - netdisco-postgresql
#networks:
#  default:
#    enable_ipv6: true
