defaults: &defaults
  docker:
    - image: circleci/ruby:2.4.1

version: 2
jobs:
  environment-setup:
    <<: *defaults
    steps:
      - checkout
      - run: |
          cd /home/circleci/project
          TAG=$(git tag -l | grep -E '^2\.[0-9]{6}' | sort -gr | head -n1 | sed -E 's/\.[0-9]{3}$//')
          echo "export IMAGE_ROOT=\"netdisco:${TAG}\"" >> $BASH_ENV

  build-netdisco-base:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: mkdir -p /tmp/workspace | true
      - run:
          name: Build netdisco-base
          command: |
            source $BASH_ENV
            cd /home/circleci/project/netdisco-base
            docker build -t ${IMAGE_ROOT}-base .
            docker save -o /tmp/workspace/netdisco-base.tar ${IMAGE_ROOT}-base
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - netdisco-base.tar

  build-netdisco-do:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir -p /tmp/workspace | true
      - run:
          name: Restore netdisco-base
          command: |
            docker load -i /tmp/workspace/netdisco-base.tar
      - run:
          name: Build netdisco-do
          command: |
            source $BASH_ENV
            cd /home/circleci/project/netdisco-do
            docker build --cache-from ${IMAGE_ROOT}-base -t ${IMAGE_ROOT}-do .
            docker save -o /tmp/workspace/netdisco-do.tar ${IMAGE_ROOT}-do
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - netdisco-do.tar

workflows:
  version: 2
  build-netdisco:
    jobs:
      - environment-setup
      - build-netdisco-base:
          requires:
            - environment-setup
      - build-netdisco-do:
          requires:
            - build-netdisco-base
