version: 2
jobs:
  build-netdisco-base:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Show Tag
          command: echo test 3
      - run:
          name: Show pwd0
          command: pwd
      - run:
          name: Show pwd
          command: cd project/ && pwd
      - run:
          name: Show pwd2
          command: cd project/ && pwd
workflows:
  version: 2
  build-netdisco:
    jobs:
      - build-netdisco-base:
          filters:
            tags:
              only: /^2\.\d{6}/
            branches:
              only: master
#              ignore: /.*/
