version: 2
jobs:
  build-netdisco-base:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: cd /root/project && echo "export HEAD_TAG=$(git tag -l | grep -E '^2\.\d{6}' | sort -gr | head -n1)" >> $BASH_ENV
      - run: . $BASH_ENV && cd /root/project && echo "export TAG=$(echo $HEAD_TAG | sed -E 's/\.\d{3}$//')" >> $BASH_ENV
      - run: cat $BASH_ENV
      - run: . $BASH_ENV && env
workflows:
  version: 2
  build-netdisco:
    jobs:
      - build-netdisco-base:
          filters:
            tags:
              only: /^2\.\d{6}/
            branches:
              only: master
#              ignore: /.*/
