version: '3.4'
services:
  netdisco-postgresql:
    image: netdisco-postgresql:latest
    build:
      context: netdisco-postgresql
    volumes:
      - "./netdisco/pgdata:/var/lib/postgresql/data"
  netdisco-base:
    image: netdisco-base:latest
    build:
      context: netdisco-base
  netdisco-backend:
    image: netdisco-backend:latest
    build:
      context: netdisco-backend
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - netdisco-postgresql:db
  netdisco-web:
    image: netdisco-web:latest
    build:
      context: netdisco-web
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - netdisco-postgresql:db
  netdisco-do:
    image: netdisco-do:latest
    build:
      context: netdisco-do
    volumes:
      - "./netdisco/config:/home/netdisco/environments"
    depends_on:
      - netdisco-base
    links:
      - netdisco-postgresql:db
